### ISSUE TITLE
Support any S3 compliant provider

### ISSUE THREAD

**Issue by imtomjorge** [cloudlena/s3manager#16]
Hello,
It could be a good idea to allow S3 compliant providers to work.

I've tried to use Scaleway and Alibaba Object Storage Service.
But as we can't modify the region, it's not working at all.

`2021/08/04 21:00:29 error listing buckets: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'`
Here I've used Scaleway, and even tried to add the env. variable "REGION", but as it doesn't exists, it can't work at all.

Thanks! :)

**Comment by mastertinner** [comment]
Thanks, @imtomjorge. I just released `v0.2.0` with support for regions. Can you test if that works for you?

**Comment by imtomjorge** [comment]
Hello,
After a fresh new deployment, the issue still persists... :( 

```
root@s3manager:~#  docker run -p 8080:8080 -e 'ENDPOINT=s3.fr-par.scw.cloud' -e 'REGION=fr-par' -e 'ACCESS_KEY_ID=MyAccessKey' -e 'SECRET_ACCESS_KEY=MySecretKey' mastertinner/s3manager
2021/08/05 17:46:02 GET	/	33.15µs
2021/08/05 17:46:02 error listing buckets: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'
2021/08/05 17:46:02 GET	/buckets	37.757674ms
2021/08/05 17:46:03 GET	/favicon.ico	27.91µs
```
I really don't understand why it doesn't work at all, even with this "region" field.

**Comment by imtomjorge** [comment]
Hello @cloudlena,
Any update? :) 
Let me know if I can help you in any way! :)

**Comment by cloudlena** [comment]
Fixed with `REGION` environment variable
